# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
        # Required to make flake8 read fdrom pyproject.toml for now :(
        additional_dependencies: ["flake8-pyproject"]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        language_version: "3.10"
        args: [--explicit-package-bases]
        additional_dependencies:
          - "sqlalchemy-stubs"
          - "sqlalchemy==1.3.22"
          - "types-pyyaml"
          - "types-requests"
          - "types-setuptools"
