services:
  sync:
    depends_on:
      - auth
      - postgres
      - rabbitmq
      - third-party-http
      - webhookd
      - oauth2.googleapis.com
      - fcm.googleapis.com
      - api.push.apple.com
    environment:
        TARGETS: "third-party-http:1080 postgres:5432 rabbitmq:5672 webhookd:9300 auth:9497 oauth2.googleapis.com:443 fcm.googleapis.com:443 api.push.apple.com:443"
