version: '3'
services:
  sync:
    depends_on:
      - postgres
      - webhookd
    environment:
      TARGETS: "postgres:5432 webhookd:9300"

  webhookd:
    volumes:
      - "./etc/wazo-webhookd/conf.d/50-default-config.base.yml:/etc/wazo-webhookd/conf.d/50-default-config.yml"
